scraping:
  lookback_days: 3  # بازه زمانی بررسی پیام‌ها (به روز)
  max_pages: 16     # حداکثر تعداد صفحات برای اسکرپ کردن در هر کانال

storage:
  base_path: "src/telegram" # محل ذخیره فایل‌های Markdown استخراج شده
