name: Update Telegram Subs

on:
#  schedule:
 #   - cron: '0 */4 * * *'
  workflow_dispatch:
    inputs:
      run_scraper:
        description: '1. Run Scraper?'
        type: boolean
        default: true
      run_extractor:
        description: '2. Run Extractor?'
        type: boolean
        default: true
      run_tester:
        description: '3. Run Tester (xray-knife)?'
        type: boolean
        default: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        pip install requests beautifulsoup4 pyyaml lxml

    - name: 1. Run Scraper
      if: github.event_name == 'schedule' || inputs.run_scraper == true
      run: python src/telegram_scraper.py

    - name: 2. Run Extractor
      if: github.event_name == 'schedule' || inputs.run_extractor == true
      run: python src/config_extractor.py

    - name: 3. Run Tester
      if: inputs.run_tester == true
      run: python src/config_tester.py

    - name: Commit Changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "Auto-update: Configs & Tested Subs [skip ci]"
        file_pattern: 'src/telegram/* sub/*'
